_target_: pytorch_lightning.Trainer

defaults:
  - default

gpus: '0'
resume_from_checkpoint:
auto_lr_find: False
deterministic: False
accelerator: null
sync_batchnorm: False

max_epochs: 30000
min_epochs: 10000
check_val_every_n_epoch: 3
num_sanity_val_steps: 1

precision: 16
amp_backend: "native"
amp_level: "O2"
